mutation register($username: String!, $email: String!, $password: String!) {
    register(username: $username, email: $email, password: $password) {
        user {
            username,
            email,
            joined,
            account
        }
        token
    }
}